services:
  marketplace:
    build: .
    volumes:
      - .:/marketplace
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    build: ./consumers
    restart: always
    env_file:
      - consumers/.env






