"""Added fields created_at and updated_at

Revision ID: 0a4a85e68b86
Revises: 8a659ead75c3
Create Date: 2024-08-05 18:34:29.297348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4a85e68b86'
down_revision: Union[str, None] = '8a659ead75c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('favorites', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('favorites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('order_statuses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_statuses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products_in_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products_in_orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('shops', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('shops', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('shops', 'updated_at')
    op.drop_column('shops', 'created_at')
    op.drop_column('products_in_orders', 'updated_at')
    op.drop_column('products_in_orders', 'created_at')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('orders', 'updated_at')
    op.drop_column('order_statuses', 'updated_at')
    op.drop_column('order_statuses', 'created_at')
    op.drop_column('favorites', 'updated_at')
    op.drop_column('favorites', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
