"""Fix orders table

Revision ID: 86d328136a57
Revises: 0a4a85e68b86
Create Date: 2024-08-23 00:04:35.398025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d328136a57'
down_revision: Union[str, None] = '0a4a85e68b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_products_in_order_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'products_in_order_id')
    op.add_column('products_in_orders', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products_in_orders', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_in_orders', type_='foreignkey')
    op.drop_column('products_in_orders', 'order_id')
    op.add_column('orders', sa.Column('products_in_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_products_in_order_id_fkey', 'orders', 'products_in_orders', ['products_in_order_id'], ['id'])
    # ### end Alembic commands ###
